### ISSUE TITLE
I have the following problems during use,thank！

### ISSUE THREAD

**Issue by yyheart** [jorhelp/Ingram#13]
![Snipaste_2022-08-07_23-00-54](https://user-images.githubusercontent.com/56282725/183297376-880a0b0e-5ef2-42a0-89d4-20a86781bab5.jpg)
$ python run_ingram.py --in test_in --out test_out --all --th 230 --nosnap
Traceback (most recent call last):
  File "C:\Users\tt\Ingram\run_ingram.py", line 68, in <module>
    run(args)
  File "C:\Users\tt\Ingram\run_ingram.py", line 48, in run
    for line in f:
UnicodeDecodeError: 'gbk' codec can't decode byte 0x80 in position 1519: illegal multibyte sequence

**Comment by jorhelp** [comment]
Sorry for that, but we didnt test our project on windows platform, perhaps you could run it on a linux pc?
