### ISSUE TITLE
cant cancel paused job

### ISSUE THREAD

**Issue by surfer663** [jorhelp/Ingram#14]
i ran Ingram but decided to stop the job with Ctrl C it then went into paused.... now i cant start another job how do i cancel the paused session and start a new session... am a newbie please forgive

**Comment by jorhelp** [comment]
Hi, if you want to run a new job, you must specific a **new OUTPUT dir**, since the programm will read the output dir and the previous output files will be loaded again.

**Comment by surfer663** [comment]
hi sir thank you for the help i appreciate it

**Comment by surfer663** [comment]
helo sir can the old OUT_DIR be deleted cos when i try the option to delete or move to trash is not available

**Comment by jorhelp** [comment]
> helo sir can the old OUT_DIR be deleted cos when i try the option to delete or move to trash is not available

Maybe you had ran masscan? masscan need root privilege, and the OUT_DIR cannot be deleted by normal user, `sudo rm -rf OUT_DIR` can work.

**Comment by surfer663** [comment]
thank u sir for always helping i used this ... ./run_ingram.py --in TARGET --out OUT_DIR --hik_weak --cve_2017_7921 --cve_2021_36260 --th_num 80

**Comment by jorhelp** [comment]
That's strange. I didn't expect where is the problem for the time being.😬😬

**Comment by surfer663** [comment]
when i use Ctrl c to cancel or stop then it is paused and can only resume cant  start another project the paused.txt cannot be deleted so i created another folder renamed original OUT_DIR1 and created a new OUT_DIR cos cannot delete as long as paused.txt is there

**Comment by jorhelp** [comment]
could you pls paste the output of `ls -l OUT_DIR`

**Comment by surfer663** [comment]
$ ls -l OUT_DIR
total 36
-rw-r--r-- 1 root root  5222 Aug 13 13:15 not_vulnerable.csv
-rw-r--r-- 1 root root  4509 Aug 13 13:11 paused
-rw-r--r-- 1 root root   580 Aug 13 08:31 results_all.csv
-rw-r--r-- 1 root root   348 Aug 13 08:31 results_simple.csv
drwxr-xr-x 2 root root 12288 Aug 13 08:31 snapshots

**Comment by surfer663** [comment]
it seems the job can only be paused and can resume but cannot be stopped

**Comment by jorhelp** [comment]
i noticed the output files are belong to root，maybe you ran the program by root or sudo，you should delete it by `sudo rm -rf OUT_DIR` if you are not root user

**Comment by surfer663** [comment]
this is how i ran it
sudo python3 run_ingram.py --in statics/iplist/data/country/US.txt  --out OUT_DIR --hik_weak --cve_2017_7921 --cve_2021_36260 --th_num 80
[sudo] password for kali:

**Comment by jorhelp** [comment]
better not ran it by root，since it not security.

**Comment by jorhelp** [comment]
😀so the 'sudo' can be delete

**Comment by surfer663** [comment]
i did it now 
$ python3 run_ingram.py --in statics/iplist/data/country/US.txt  --out OUT_DIR --hik_weak --cve_2017_7921 --cve_2021_36260 --th_num 80 

this the error

Traceback (most recent call last):
  File "/home/kali/Desktop/Ingram/run_ingram.py", line 68, in <module>
    run(args)
  File "/home/kali/Desktop/Ingram/run_ingram.py", line 59, in run
    else: scn = scanner.CameraScanner(args)
  File "/home/kali/Desktop/Ingram/scan/scanner.py", line 59, in __init__
    self._preprocess()
  File "/home/kali/Desktop/Ingram/scan/scanner.py", line 76, in _preprocess
    self.paused = open(os.path.join(self.args.out_path, PAUSE), 'r+')
PermissionError: [Errno 13] Permission denied: 'OUT_DIR/paused'
Exception ignored in: <function CameraScanner.__del__ at 0x7f3c4a379ea0>
Traceback (most recent call last):
  File "/home/kali/Desktop/Ingram/scan/scanner.py", line 91, in __del__
    if os.path.exists(os.path.join(self.args.out_path, PAUSE)): self.paused.close()
AttributeError: 'CameraScanner' object has no attribute 'paused'

**Comment by jorhelp** [comment]
the privous OUT_DIR can be delete by`sudo rm -rf`, after that, when you runa new job, just run ./run_Ingram ...etc...  and not add 'sudo', so the OUT_DIR can be direcly removed

**Comment by surfer663** [comment]
ok thank you sir i will try that

**Comment by jorhelp** [comment]
maybe you can specifc different out dir by your job, for example, if you scan Japan, you can let --out be japan, if you scan china, you can let --out be china.

**Comment by surfer663** [comment]
that a good idea sir i will try that as well...please can you tell me me how i can add my own ip and country list to the HIK_WEAK  to scan and also to use the masscan option
thank you

**Comment by jorhelp** [comment]
its 2:00 here, i will reply tomorrow, see you later😴😴

**Comment by surfer663** [comment]
no problem thank you sir

**Comment by jorhelp** [comment]
+ if you want to use masscan, you should install it by your self first, after that, run:
```bash
./run_ingram.py --in TARGET --out OUT_DIR --masscan --port 80,8000-8008 --rate 5000
./run_ingram.py --in OUT_DIR/masscan_res --out OUT_DIR --all --th_num 80
```

+ if you want to scan some ips, you should add it to the TARGET file, one ip one line;  and the `statics/iplist/data/country/` dir contain many country's ip, you can take any one of them as the TARGET, such as:
```bash
./run_ingram.py --in statics/iplist/data/country/JP.txt --out japan --all --th_num 80
```

**Comment by surfer663** [comment]
thank you sir i really appreciate the help i tried it and it works perfect.... mayb next ya can do something for the NVR and DVR for truvision and Alibi just a thought lol 
many thanks

**Comment by surfer663** [comment]
hi sir i got usernames and passwords but when i use IE to login i cant view the cameras why is that or what to do to view

**Comment by surfer663** [comment]
> hi sir i got usernames and passwords but when i use IE to login i cant view the cameras why is that or what to do to view

dont worry sir i updated the camera plugin and it works now

**Comment by surfer663** [comment]
hi sir can you tell me why im getting this error

[-] FAIL: could not determine default interface
    [hint] try "--interface ethX"
Traceback (most recent call last):
  File "/home/kali/Desktop/Ingram/run_ingram.py", line 68, in <module>
    run(args)
  File "/home/kali/Desktop/Ingram/run_ingram.py", line 60, in run
    scn()
  File "/home/kali/Desktop/Ingram/scan/scanner.py", line 45, in __call__
    self.parse(self.tmp)
  File "/home/kali/Desktop/Ingram/scan/scanner.py", line 32, in parse
    with open(tmp, 'r') as tf:
FileNotFoundError: [Errno 2] No such file or directory: 'OUT_DIR/masscan_tmp'

**Comment by WarRaZzer** [comment]
i get every time 
PermissionError: [WinError 32]

**Comment by jorhelp** [comment]
We will be releasing the latest version soon, which is less problematic
