### ISSUE TITLE
提示target.txt 文件不存在，是我target.txt 文件放错位置了，还是target.txt 文件里的IP地址格式不对。

### ISSUE THREAD

**Issue by fdgikog** [jorhelp/Ingram#45]
(.venv) C:\Users\Administrator\Ingram>python run_ingram.py -i target.txt -o sda

          _    __..-:┑
   ║`====╩=╩=======╣ |
==#║_______███_/ @ ║ |
   ╚===.===╦==╦=╤==╩#█
       \___║::║/         _______
           ║::║|        |_     _| .-----. .-----. .----. .---.-. .--------.
           ║::║|         _|   |_  |     | |  _  | |   _| |  _  | |        |
           ║::║_\       |_______| |__|__| |___  | |__|   |___._| |__|__|__|
            ██                            |_____|
            ██
            ██
            ██
            ██

the input file target.txt does not exists!

target.txt文件我就如下这样保存的：

# 你可以使用井号(#)来进行注释
# IP 地址以及要扫描的端口
# 带 '-' 的IP段
212.67.1.2-212.81.255.255

纯小白，学习一天了 最后到进行到the input file target.txt does not exists! 不知道怎么回事了，前面磕磕绊绊但都解决了。

**Comment by jorhelp** [comment]
你这个 IP 地址段也有问题，这个区间不太对

**Comment by fdgikog** [comment]
谢谢作者大哥的回复，本来就是抱着试一试的心态 问的问题，没想到大哥真的回复了，万份惊喜，又感觉我可以了，哈哈。
1. ip地址段是我随便写的，这个是只能用内网ip段，还是公网的ip段也可以用？
还有个疑问，
2.  这个python run_imgran.py -i XXX -o XXX命令是在(.venv) C:\Users\Administrator\Ingram> 这个路径下运行 
还是在(.venv) C:\Users\Administrator\Ingram\.venv\Scripts>python
Python 3.11.1 (tags/v3.11.1:a7a450f, Dec  6 2022, 19:58:39) [MSC v.1934 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>>
这个路径下运行？
我是对电脑感兴趣，纯属自学，所以问题看起来有点奇怪，哈哈。

3.现在txt文件可以找到了，但是出现了新的问题，如下：
(.venv) C:\Users\Administrator\Ingram>python run_ingram.py -i target.txt -o sda

          _    __..-:┑
   ║`====╩=╩=======╣ |
==#║_______███_/ @ ║ |
   ╚===.===╦==╦=╤==╩#█  |''||''|
       \___║::║/           ||
           ║::║|           ||     `||''|,   .|''|,  '||''|   '''|.   '||),,(|,
           ║::║|           ||      ||  ||   ||  ||   ||     .|''||    || || ||
           ║::║_\       |..||..|  .||  ||.  `|..||  .||.    `|..||.  .||    ||.
            ██                                  ||
            ██                               `..|'
            ██
            ██
            ██

Exception in thread Thread-3 (get_data_from_disk):
Traceback (most recent call last):
[⇐] 0/0(0.0%)   Time: 0s/0s          File "E:\Python\Python311\Lib\threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "E:\Python\Python311\Lib\threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\Administrator\Ingram\Ingram\core\data.py", line 39, in get_data_from_disk
    for line in f:
UnicodeDecodeError: 'gbk' codec can't decode byte 0xb7 in position 22: illegal multibyte sequence
[⇑] 0/0(0.0%)   Time: 0s/0s

谢谢作者大哥

**Comment by fdgikog** [comment]
ok，我会把虚拟机装上Linux系统，只是装系统的话应该不难 哈哈
