### ISSUE TITLE
无法运行，有“ValueError: negative shift count”错误提示

### ISSUE THREAD

**Issue by hdy99** [jorhelp/Ingram#63]
运行错误提示：
Exception in thread Thread-1 (_cal_total):
Traceback (most recent call last):
  File "K:\Python310\lib\threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "K:\Python310\lib\threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "K:\Ingram\Ingram\data.py", line 54, in _cal_total
    self.add_total(net.get_ip_seg_len(strip_line))
  File "K:\Ingram\Ingram\utils\net.py", line 16, in get_ip_seg_len
    return IPy.IP(ip_seg, make_net=True).len()
  File "K:\Python310\lib\site-packages\IPy.py", line 259, in __init__
    self.ip = self.ip & _prefixlenToNetmask(self._prefixlen, self._ipversion)
  File "K:\Python310\lib\site-packages\IPy.py", line 1632, in _prefixlenToNetmask
    return ((2<<prefixlen-1)-1) << (_ipVersionToLen(version) - prefixlen)
ValueError: negative shift count
error occurred, see the log.txt for more information.

**Comment by newplaydan** [comment]
我有同样的错误显示，IP无法跑完，烦请修复

**Comment by a5613273** [comment]
一样，我也是这样报错
