### ISSUE TITLE
error occurred, see the log.txt for more information???

### ISSUE THREAD

**Issue by halstead7** [jorhelp/Ingram#68]
someone solved this?

**Comment by AndyDuPB** [comment]
Same as me

**Comment by gencturk39** [comment]
answer please

**Comment by o0oo0ooo0** [comment]
Create a new snapshots directory under the output directory (that is, the directory after -o).

**Comment by messi66633** [comment]
> Create a new snapshots directory under the output directory (that is, the directory after -o).

What system do you use? Why do I always report errors?

**Comment by monera78** [comment]
Exception ignored in: <finalize object at 0x7ff025cdbfa0; dead>
Traceback (most recent call last):
  File "/home/codespace/.python/current/lib/python3.10/weakref.py", line 591, in __call__
    return info.func(*info.args, **(info.kwargs or {}))
  File "/workspaces/xmwode/Ingram/venv/lib/python3.10/site-packages/urllib3/connectionpool.py", line 1178, in _close_pool_connections
    conn = pool.get(block=False)
  File "/home/codespace/.python/current/lib/python3.10/queue.py", line 182, in get
    self.not_full.notify()
  File "/home/codespace/.python/current/lib/python3.10/threading.py", line 369, in notify
    if not self._is_owned():
  File "/home/codespace/.python/current/lib/python3.10/threading.py", line 282, in _is_owned
    if self._lock.acquire(False):
  File "/workspaces/xmwode/Ingram/venv/lib/python3.10/site-packages/gevent/thread.py", line 132, in acquire
    sleep()
  File "/workspaces/xmwode/Ingram/venv/lib/python3.10/site-packages/gevent/hub.py", line 159, in sleep
    waiter.get()
  File "src/gevent/_waiter.py", line 143, in gevent._gevent_c_waiter.Waiter.get
  File "src/gevent/_waiter.py", line 154, in gevent._gevent_c_waiter.Waiter.get
  File "src/gevent/_greenlet_primitives.py", line 61, in gevent._gevent_c_greenlet_primitives.SwitchOutGreenletWithLoop.switch
  File "src/gevent/_greenlet_primitives.py", line 61, in gevent._gevent_c_greenlet_primitives.SwitchOutGreenletWithLoop.switch
  File "src/gevent/_greenlet_primitives.py", line 65, in gevent._gevent_c_greenlet_primitives.SwitchOutGreenletWithLoop.switch
  File "src/gevent/_gevent_c_greenlet_primitives.pxd", line 35, in gevent._gevent_c_greenlet_primitives._greenlet_switch
TimeoutError: timed out

**Comment by paulfarrowuk** [comment]
I had similar issues - just check that your output directory has a directory named 'snapshots' in it. If not, create the 'snapshots' directory.

**Comment by csx98** [comment]
> Create a new snapshots directory under the output directory (that is, the directory after -o).

Thank you for your prompt
