### ISSUE TITLE
启动报语法错误，今天克隆的最新版

### ISSUE THREAD

**Issue by bunahua** [jorhelp/Ingram#80]
(venv) [xxxxx@xxxx Ingram-master]# python3 run_ingram.py -i target.txt -o .
`Traceback (most recent call last):
  File "run_ingram.py", line 18, in <module>
    from Ingram import get_config
  File "/root/Ingram-master/Ingram/__init__.py", line 1, in <module>
    from .config import get_config
  File "/root/Ingram-master/Ingram/config.py", line 41
    for arg in (args := vars(args)):
                     ^
SyntaxError: invalid syntax
(venv) [root@root Ingram-master]# `

**Comment by weandy** [comment]
+1 解决了吗

**Comment by f0ng** [comment]
升级py到3.8+即可解决
